on:
    schedule:
        - cron: "0 8,16 * *  *" #Runs every minute, at 08:00 and 16:00
    workflow_dispatch:

jobs:
  pre-code-checkout:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Trivy vuln checkout
      uses: aquasecurity/trivy-action@v0.36.0
      with:
        scan-type: 'fs'
        scan-ref: './'
   
    
  automation-stat-checking:
      needs: 'pre-code-checkout'
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v5

          - name: Run code
            run: |
              docker compose up -d --build
            
          - name: Show statistics
            run: |
              sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" ./logs/* >> $GITHUB_STEP_SUMMARY #Deleting symbols that should show colourful outpu
